# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv
  FEATURIZED_DATA: features
  FEATURIZED_TRAIN_DATA: train.pkl
  FEATURIZED_TEST_DATA: test.pkl
  MODEL_DIR: model
  MODEL_NAME: model.pkl

source_data_url: https://drive.google.com/uc?export=download&confirm=9_s_&id=1A59dnUwOgG3CXbq-ni2cykd7yZxaYTqH

source_download_dir:
  data_dir: data
  data_file: data.xml


local_data_dirs:
  - path_to_local_data_1
  - path_to_local_data_2

plots:
  PRC: prc.json
  ROC: roc.json
metrics:
  SCORES: scores.json