name: DVC-NLP-usecase

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python_version: '3.9'
      - name: cml-run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #your MLworkdlow commnds
          pip install --upgrade pip
          pip install -r requirements.txt
          
          dvc repro --no-run-cache -v

          echo "# REPORTS" >> report.md
          echo "## metrics" >> report.md
          cat scores.json >> report.md

          cml-send-comment report.md




